# Generated by Django 4.2.13 on 2024-05-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_marca_estado_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
